name: Deploy Demo

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: latest

      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: true

      - run: pnpm run build
        working-directory: vue

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          silent: true
          clean: true
          branch: gh-pages
          folder: vue/dist
          single-commit: true
